# This is a generated file. Not intended for manual editing.
services:
  order.api:
    build:
      context: "/Users/tungle/Data Local/OpenAPI"
      dockerfile: "Order/src/Order.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Order.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "orderapi:dev"
    ports: []
    volumes:
    - "/Users/tungle/Data Local/OpenAPI/Order/src/Order.API:/app:rw"
    - "/Users/tungle/Data Local/OpenAPI:/src:rw"
    - "/Users/tungle/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
